#!/usr/bin/env python3
"""
Build script for Durak Online.

Reads src/templates/*, src/styles/*, src/js/* and config.json, and writes a
self-contained static site to dist/ that GitHub Pages can serve as-is.

No dependencies beyond the Python standard library.

    python3 build.py            # build once into dist/
    python3 build.py --serve    # build, then serve dist/ on localhost:8000
    python3 build.py --watch    # rebuild whenever a source file changes

Template syntax (deliberately tiny):

    {{ include "partials/lobby.html" }}   splice in another template
    {{ config.site.title }}              dotted lookup into config.json
    {{ asset "styles/main.css" }}        emit a content-hashed URL
    {{ build.hash }} / {{ build.date }}  build metadata
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
SRC = ROOT / "src"
TEMPLATES = SRC / "templates"
DIST = ROOT / "dist"
CONFIG_PATH = ROOT / "config.json"

TAG = re.compile(r"\{\{\s*(.*?)\s*\}\}")
MAX_INCLUDE_DEPTH = 12


class BuildError(Exception):
    pass


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #

def load_config() -> dict:
    if not CONFIG_PATH.exists():
        raise BuildError("config.json is missing. Copy config.example.json to config.json.")
    try:
        config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as err:
        raise BuildError(f"config.json is not valid JSON: {err}") from err

    for key in ("site", "supabase", "game"):
        if key not in config:
            raise BuildError(f'config.json is missing the "{key}" section.')

    base = config["site"].get("basePath", "/")
    if not base.startswith("/"):
        base = "/" + base
    if not base.endswith("/"):
        base += "/"
    config["site"]["basePath"] = base
    return config


def lookup(config: dict, dotted: str):
    """config.site.title -> config['site']['title']"""
    node = config
    for part in dotted.split("."):
        if not isinstance(node, dict) or part not in node:
            raise BuildError(f"config.json has no value at {dotted!r}")
        node = node[part]
    if isinstance(node, (dict, list)):
        raise BuildError(f"{dotted!r} is a {type(node).__name__}, not a value")
    return node


def short_hash(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:10]


def read_template(name: str) -> str:
    path = TEMPLATES / name
    if not path.exists():
        raise BuildError(f"template not found: {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8")


# --------------------------------------------------------------------------- #
# rendering
# --------------------------------------------------------------------------- #

def render(text: str, ctx: dict, depth: int = 0) -> str:
    if depth > MAX_INCLUDE_DEPTH:
        raise BuildError("include depth exceeded — is a template including itself?")

    def replace(match: re.Match) -> str:
        expr = match.group(1)

        if expr.startswith("include "):
            target = expr[len("include "):].strip().strip("\"'")
            return render(read_template(target), ctx, depth + 1)

        if expr.startswith("asset "):
            target = expr[len("asset "):].strip().strip("\"'")
            url = ctx["assets"].get(target)
            if url is None:
                raise BuildError(f"unknown asset {target!r} — is it under src/?")
            return url

        if expr.startswith("build."):
            return str(ctx["build"][expr.split(".", 1)[1]])

        if expr.startswith("config."):
            return str(lookup(ctx["config"], expr[len("config."):]))

        raise BuildError(f"unrecognised template tag: {{{{ {expr} }}}}")

    return TAG.sub(replace, text)


def write_js_config(config: dict, build_hash: str) -> None:
    """
    Emit src config as a real JS module so the app never has to fetch and
    await a JSON file before it can boot.

    The Supabase anon key belongs in here. It is designed to be public — see
    README, "Why the anon key is in the repo".
    """
    payload = {
        "supabaseUrl": config["supabase"]["url"],
        "supabaseAnonKey": config["supabase"]["anonKey"],
        "defaultPlayers": config["game"].get("defaultPlayers", 4),
        "turnSeconds": config["game"].get("turnSeconds", 0),
        "basePath": config["site"]["basePath"],
        "buildHash": build_hash,
    }
    body = (
        "// Generated by build.py. Edit config.json instead — this file is overwritten.\n"
        f"export const CONFIG = Object.freeze({json.dumps(payload, indent=2)});\n"
    )
    (DIST / "js" / "config.js").write_text(body, encoding="utf-8")


def collect_assets(config: dict) -> dict:
    """
    Copy css/js into dist and return a map of source path -> served URL.

    CSS gets a content hash in the filename. JS keeps stable filenames because
    ES module imports reference each other by path; the entry point carries a
    ?v= query instead, which is enough to bust the 10-minute Pages cache.
    """
    base = config["site"]["basePath"]
    assets: dict[str, str] = {}

    (DIST / "styles").mkdir(parents=True, exist_ok=True)
    for css in sorted((SRC / "styles").glob("*.css")):
        data = css.read_bytes()
        name = f"{css.stem}.{short_hash(data)}.css"
        (DIST / "styles" / name).write_bytes(data)
        assets[f"styles/{css.name}"] = f"{base}styles/{name}"

    audio_src = SRC / "audio"
    if audio_src.is_dir():
        (DIST / "audio").mkdir(parents=True, exist_ok=True)
        for clip in sorted(audio_src.iterdir()):
            if clip.is_file():
                shutil.copy2(clip, DIST / "audio" / clip.name)

    (DIST / "js").mkdir(parents=True, exist_ok=True)
    js_bytes = json.dumps(config, sort_keys=True).encode()  # config ships inside js/config.js
    for js in sorted((SRC / "js").glob("*.js")):
        data = js.read_bytes()
        js_bytes += data
        (DIST / "js" / js.name).write_bytes(data)
    js_hash = short_hash(js_bytes)
    for js in sorted((SRC / "js").glob("*.js")):
        assets[f"js/{js.name}"] = f"{base}js/{js.name}?v={js_hash}"

    return assets, js_hash


def verify_hidden_works(css_text: str) -> None:
    """
    Views are toggled with the `hidden` attribute. That gets display:none from
    the browser's default stylesheet, which any author rule setting `display`
    overrides — so a single `.panel { display: grid }` can make an element
    impossible to hide. Fail the build unless the stylesheet restates it.
    """
    if not re.search(r"\[hidden\][^{]*\{[^}]*display\s*:\s*none\s*!important", css_text):
        raise BuildError(
            "stylesheet must contain `[hidden] { display: none !important; }` — "
            "without it, any rule setting `display` stops `hidden` from working"
        )


def build() -> None:
    started = time.perf_counter()
    config = load_config()

    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir(parents=True)

    css_text = "\n".join(p.read_text(encoding="utf-8") for p in (SRC / "styles").glob("*.css"))
    verify_hidden_works(css_text)

    assets, js_hash = collect_assets(config)
    write_js_config(config, js_hash)

    ctx = {
        "config": config,
        "assets": assets,
        "build": {
            "hash": js_hash,
            "date": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        },
    }

    html = render(read_template("base.html"), ctx)
    (DIST / "index.html").write_text(html, encoding="utf-8")

    # Pages serves 404.html for unknown paths; hand it back to the SPA router.
    (DIST / "404.html").write_text(html, encoding="utf-8")
    # Stop Pages from running the content through Jekyll.
    (DIST / ".nojekyll").write_text("", encoding="utf-8")

    if config["supabase"]["url"].startswith("https://YOUR-"):
        print("  note: config.json still has placeholder Supabase credentials.")

    kb = len(html.encode()) / 1024
    elapsed = (time.perf_counter() - started) * 1000
    print(f"Built dist/ in {elapsed:.0f}ms — index.html {kb:.1f}kB, assets hash {js_hash}")


# --------------------------------------------------------------------------- #
# dev conveniences
# --------------------------------------------------------------------------- #

def source_fingerprint() -> str:
    h = hashlib.sha256()
    for path in sorted(SRC.rglob("*")):
        if path.is_file():
            h.update(path.name.encode())
            h.update(path.read_bytes())
    if CONFIG_PATH.exists():
        h.update(CONFIG_PATH.read_bytes())
    return h.hexdigest()


def watch() -> None:
    print("Watching src/ and config.json. Ctrl-C to stop.")
    last = None
    while True:
        current = source_fingerprint()
        if current != last:
            try:
                build()
            except BuildError as err:
                print(f"  build failed: {err}", file=sys.stderr)
            last = current
        time.sleep(0.6)


def serve(port: int) -> None:
    import functools
    from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

    handler = functools.partial(SimpleHTTPRequestHandler, directory=str(DIST))
    print(f"Serving dist/ at http://localhost:{port}/  (Ctrl-C to stop)")
    ThreadingHTTPServer(("127.0.0.1", port), handler).serve_forever()


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the Durak Online site.")
    parser.add_argument("--serve", action="store_true", help="serve dist/ after building")
    parser.add_argument("--watch", action="store_true", help="rebuild on source changes")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()

    try:
        if args.watch:
            watch()
            return 0
        build()
        if args.serve:
            serve(args.port)
    except BuildError as err:
        print(f"Build failed: {err}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\nStopped.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
